PROJECT=RS232Bootstrap
MANIFEST=manifest.rtl
BOARDS_ALTERA = "de0 de1 de2 coreboard chameleon64 mist"
BOARDS_XILINX = "ems11_bb37"

all:
	make -f ../Scripts/standard.mak PROJECT=$(PROJECT) BOARDS_ALTERA=$(BOARDS_ALTERA) BOARDS_XILINX=$(BOARDS_XILINX)

clean:
	make -f ../Scripts/standard.mak PROJECT=$(PROJECT) BOARDS_ALTERA=$(BOARDS_ALTERA) BOARDS_XILINX=$(BOARDS_XILINX) clean

