all:
	make -C Dhrystone
	make -C Filesystem
	make -C HelloWorld
	make -C JPEGTest
	make -C Malloc
	make -C VGA

clean:
	make -C Dhrystone clean
	make -C Filesystem clean
	make -C HelloWorld clean
	make -C JPEGTest clean
	make -C Malloc clean
	make -C VGA clean

